### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by f1vefour** [5axes/Cura-Postprocessing-Scripts#1]
Does this simply add the Cura settings to the gcode or can you somehow extract these into Cura as well?

I ask because people always want to know my settings so they can use them and often Cura fails to import profiles exported from a different version.

Either way it’s a beautiful script and I thank you.

**Comment by 5axes** [comment]
No this script just add some comments in the Gcode.   I don't think it's possible to get back your settings via this way. But one day via a PlugIn it will be possible; that's something I'm thinking about.

**Comment by f1vefour** [comment]
Thanks for the answer, I will go ahead and close this issue.

**Comment by 5axes** [comment]
https://github.com/5axes/ImportExportProfiles
