### ISSUE TITLE
FastFirstInfill not working

### ISSUE THREAD

**Issue by morsyfadl** [5axes/Cura-Postprocessing-Scripts#10]
Hi.
I've been looking for days for a way to do this then I found FastFirstInfill only to find its not working. 
Is it because of changes made to 5.x? is there any way to fix it possibly?

**Comment by 5axes** [comment]
Need to check. I m using it every time on 5.x and also 4.20 ... what is your printer, canbyou share a sample project ?

**Comment by morsyfadl** [comment]
test

**Comment by morsyfadl** [comment]
It doesnt even appear in the GUI for me. I havent Installed a custom script before so probably im doing somthing wrong.
I tried putting the .py file in both these locations:
"C:\Users\(me)\AppData\Roaming\cura\5.5\scripts"
"C:\Program Files\UltiMaker Cura 5.5.0\share\cura\plugins\PostProcessingPlugin\scripts"

This is what I see when I open cura
![image](https://github.com/5axes/Cura-Postprocessing-Scripts/assets/35445029/29a9f8b9-a3e3-4a23-9296-8774235e650a)

**Comment by 5axes** [comment]
It's the correct location .. The script should be visible in the list.

![image](https://github.com/5axes/Cura-Postprocessing-Scripts/assets/11015345/8065faa6-17f8-467f-9cb3-686bd2eb5d76)

Can you share your log file ?

**Comment by morsyfadl** [comment]
Here it is. [cura.zip](https://github.com/5axes/Cura-Postprocessing-Scripts/files/13635777/cura.zip)

I found the following error multiple times in it for both the FastFirstInfill and MultiBrim but i have no idea what it means

> <title>Cura-Postprocessing-Scripts/FastFirstInfill.py at master · 5axes/Cura-Postprocessing-Scripts</title>
> 2023-12-09 23:04:25,403 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [227]:                                                                     ^
> 2023-12-09 23:04:25,403 - ERROR - [MainThread] PostProcessingPlugin.PostProcessingPlugin.loadScripts [227]: SyntaxError: invalid character '·' (U+00B7)

**Comment by 5axes** [comment]
It looks like you've saved the file in HTML format ... 

Did you use the **Download raw file** function?

![image](https://github.com/5axes/Cura-Postprocessing-Scripts/assets/11015345/73b6cb0e-fc7c-4e3b-acaa-4c14ac251e38)

**Comment by morsyfadl** [comment]
I did so once by mistake and then downloaded the true .py file size ~466kb
So in order to make things easier I did a fresh install of cura 5.6. Here's the new much shorter log file 
[cura.log](https://github.com/5axes/Cura-Postprocessing-Scripts/files/13640110/cura.log)

**Comment by 5axes** [comment]
File "C:\Users\Fadl\AppData\Roaming\cura\5.6\scripts\FastFirstInfill.py", line 99

<title>Cura-Postprocessing-Scripts/FastFirstInfill.py at master · 5axes/Cura-Postprocessing-Scripts</title>

Not normal <title></title> are HTML balise should not be present in the code . The file is certainly not the right one

**Comment by morsyfadl** [comment]
Alright its working. Turns out yes I downloaded the file in a wring way. 
Many thanks for the great work
