### ISSUE TITLE
Layer numbering in "Pause at height"

### ISSUE THREAD

**Issue by yet-another-average-joe** [5axes/Cura-Postprocessing-Scripts#11]
The description for "Pause Layer" says "Enter the Number of the LAST layer you want to finish prior to the pause. Note that 0 is the first layer..."

Seems to me it doesn't work this way. Making 4 layers labels, the background being two layers, and the text being two layers, have to enter 2 in order to get text printed as third and fourth layers. 1+2 = background, 3+4 = text ; same numbering as Cura preview.

Shouldn't the help bubble say  "Note that 1 is the first layer" ?

**Comment by 5axes** [comment]
I Don't know, "Pause at Height" is a standard Script not mine and I rarely using it.
