### ISSUE TITLE
*int* instead of *float*

### ISSUE THREAD

**Issue by tispokes** [5axes/Cura-Postprocessing-Scripts#2]
Hi, I was using your genius post processing script atm.
In particular the TempFanTower.
Was wondering if `Change Layer` and `Change Layer Offset` meant to be in *mm* cuz it's a float and layers alwas int. So i was struggeling a bit and want to check inside the code whats going on.

Whats about changing them into int? Or any specific reasons why it is a float? At the end you're casting it back to a int.
Temp and TempIncrement may seems okay with float.

Looking forward to discuss about :-) Hope it's okay that I use the issue-tool

Lars

**Comment by 5axes** [comment]
In the script repository the "release" of this script is an old version and these values are defined as *float*  in the Calibration cura plugin repository it's *int*  both are working, but it's better to define as *Int* as some user as the same confusion. They don't now if it's a number of layer or the layer height.

**Comment by 5axes** [comment]
Should be solved
