### ISSUE TITLE
what version of cura does Multibrim.py this work with

### ISSUE THREAD

**Issue by blayno** [5axes/Cura-Postprocessing-Scripts#4]
Hi im trying to use the Multibrim.py script, i have tried with cura versions 4.13.1 and 5.0 but it does not work, theres no extra brims in the preview, please help i really wanna use this post processing script

**Comment by 5axes** [comment]
Postprocessing script are active just when you postprocess the code. So there is no modification of the preview. These script should work with any release of Cura

**Comment by blayno** [comment]
Ah i see, thank you, i tried a cpl test prints with a calibration cube, Multibrim works fine in cura 4.13.1, awesome, but...  it does not work in cura 5.0, any chance we can get an updated script for cura 5.0 at all please ??? i would happily make a donation
