### ISSUE TITLE
Multibrim .py Doesnt work with cura 5.0

### ISSUE THREAD

**Issue by blayno** [5axes/Cura-Postprocessing-Scripts#5]
Multibrim Successfully installed on cura 4.13.1 and cura 5.0, Multibrim tested and works on cura 4.13.1 but it does not work on cura 5.0, no extra brim is printed, can we please get an updated script for cura 5.0 ?? i will happily make a donation

**Comment by 5axes** [comment]
###  Cura 4.X
                # G0 F6000 X106.445 Y116.579 Z0.2      -> StartLine
                # ;TYPE:SKIRT
                # G1 F3000 E0                                       -> ZHopLine/ELine
                # G1 F1200 X106.693 Y116.356 E0.011 -> SpeedLine

![image](https://user-images.githubusercontent.com/11015345/179402863-0e70cab2-e5ca-4f5d-92ae-93e59115995a.png)

### Cura 5.0                
                # G0 F6000 X105.91 Y115.98 Z0.2
                # G0 X105.3 Y117.5                                -> StartLine  Missing Z Value
                # ;TYPE:SKIRT
                # G1 F1500 E0                                         -> ZHopLine/ELine
                # G1 F1200 X105.34 Y117.083 E0.01393 -> SpeedLine

![image](https://user-images.githubusercontent.com/11015345/179402872-a2fd93c3-ffd4-49e6-acc9-691617bad544.png)

**Comment by blayno** [comment]
Cheers bud, tried and tested on cura 5.0, all working now, cheers heaps where can i make my donation ??

**Comment by 5axes** [comment]
https://ko-fi.com/5axes   

Enjoye it
