### ISSUE TITLE
Post Processing Scripts not saving

### ISSUE THREAD

**Issue by Tom-kt** [5axes/Cura-Postprocessing-Scripts#6]
The retraction tower only goes to 5mm. I need up to 7mm. I followed the instructions to open Post Processing Script. I changed the value from 5 to 7. How does it save? I clicked on close. Closed Cura (5.1), reopened it and it still is only 5 tall(5mm). Now by the slice button, there is a </>1 next to it.
![image](https://user-images.githubusercontent.com/61211047/185169227-b4dbf904-dbeb-4269-a648-16950ce034f2.png)
If I click on the </>1 it goes back to the Post Processing Script with the change made. But it doesn't change the tower.

**Comment by 5axes** [comment]
Change
Slice
Generate the GCode
