### ISSUE TITLE
PostProcessing Plugins

### ISSUE THREAD

**Issue by GregValiant** [5axes/Cura-Postprocessing-Scripts#7]
Hello @5axes 
I have been fooling around with Python and post-processors.  I have a re-write of "Insert at Layer Change" that is finished and works.  I added support for multi-line insertions, start and end layers, and options for insertion at every layer, every 2nd, 3rd, 5th, 10th, 25th, 50th and 100th (that seemed like enough).  I'm not savvy enough to do a proper pull-request and at any rate it could use another set of eyeballs as I'm not good with Python.
The other project is a work-in-progress and I've taken it as far as I can.  It's the Cooling Profile post-processor.  I've got it loading properly and the dialog boxes appear to be correct.  It doesn't work though.  I think it's throwing errors when splitting a string and moving the data to a list "Layer/FanPercentage" (as "1123/50").  I think I have a good start to it and maybe you would care to take over or maybe steer me in the right direction.
You will notice that I've modestly named them after myself.  That was actually to keep from over-writing the stock files.
If you want to disregard this I'll understand..

[GregVInsertAtLayerChange.zip](https://github.com/5axes/Cura-Postprocessing-Scripts/files/10475399/GregVInsertAtLayerChange.zip)

[GregVCoolingProfile.zip](https://github.com/5axes/Cura-Postprocessing-Scripts/files/10475400/GregVCoolingProfile.zip)

My thoughts on the cooling profile design:
Remove all the M106 lines from the file.
Pull in {machine_scale_fan_speed_zero_to_one} from Cura.
If "by Layer" then the strings are split and the list is created.  My thought was that it should be fixed length and so I've entered place keepers if a user doesn't need al 12 insertion options.  As each value is appended to the list the actual fan speed is calculated and appended instead of the percent.  There is an "if" for fan_mode 0 to 1 or 0 to 255.
As the gcode is parsed - lines with ";LAYER:" trigger a search through the list (called fan_array in the code) for a match.  When a layer match is found then the new M106 string is put together and inserted.
If the user selects "By Feature" then the Layer setting boxes are disabled and the By Feature boxes are enabled.  The fan speed for each feature is stored.  There is a possible start and end layer.  The data is parsed and every time a "TYPE:SKIRT" or "TYPE:WALL:INNER", etc.  is encountered then the corresponding fan line is assembled and inserted.  This goes on from the Start Layer to either the user defined End Layer, or to the end of the file.  If the user selected an "end layer" than at that layer the "Final Fan Speed" is inserted.
Lastly, in either case, since all the M106 lines were removed (or maybe commented out) then M106 S0 needs to be inserted when ";End of Gcode" line is encountered.

So that's it.  I've typed a little bit.  All that's left is everything else.

I'd appreciate if you would let me know what you think.

Greg (Valiant) Foresi

**Comment by GregValiant** [comment]
This is tonights effort on the Cooling profile.  I cleaned it up a bit.  I got rid of some code I thought might be causing problems when fetching and appending the variable values.

[GregVCoolingProfile2.zip](https://github.com/5axes/Cura-Postprocessing-Scripts/files/10476056/GregVCoolingProfile2.zip)

**Comment by 5axes** [comment]
It's a complex work... The script is already well advanced but there are a lot of errors and the correction will take time.  Some errors already corrected. 

https://github.com/5axes/Cura-Postprocessing-Scripts/blob/master/GregVCoolingProfile.py

**Comment by 5axes** [comment]
can close this issue
